package configrepository

const (
	extraContentKey                 = "extra_page_content"
	streamTitleKey                  = "stream_title"
	chatNameReservationDaysKey      = "chat_name_reservation_days"
	viewerUsernameKey               = "viewer_username"
	viewerPasswordHashKey           = "viewer_password_hash"
	adminPasswordKey                = "admin_password_key"
	logoPathKey                     = "logo_path"
	logoUniquenessKey               = "logo_uniqueness"
	serverSummaryKey                = "server_summary"
	serverWelcomeMessageKey         = "server_welcome_message"
	serverNameKey                   = "server_name"
	serverURLKey                    = "server_url"
	httpPortNumberKey               = "http_port_number"
	httpListenAddressKey            = "http_listen_address"
	websocketHostOverrideKey        = "websocket_host_override"
	rtmpPortNumberKey               = "rtmp_port_number"
	serverMetadataTagsKey           = "server_metadata_tags"
	socialHandlesKey                = "social_handles"
	peakViewersSessionKey           = "peak_viewers_session"
	peakViewersOverallKey           = "peak_viewers_overall"
	lastDisconnectTimeKey           = "last_disconnect_time"
	ffmpegPathKey                   = "ffmpeg_path"
	nsfwKey                         = "nsfw"
	videoLatencyLevel               = "video_latency_level"
	videoStreamOutputVariantsKey    = "video_stream_output_variants"
	chatDisabledKey                 = "chat_disabled"
	externalActionsKey              = "external_actions"
	customStylesKey                 = "custom_styles"
	customJavascriptKey             = "custom_javascript"
	videoCodecKey                   = "video_codec"
	videoSegmentFormatKey           = "video_segment_format"
	srtServerEnabledKey             = "srt_server_enabled"
	srtServerPortKey                = "srt_server_port"
	srtPassphraseKey                = "srt_passphrase"
	blockedUsernamesKey             = "blocked_usernames"
	publicKeyKey                    = "public_key"
	privateKeyKey                   = "private_key"
	serverInitDateKey               = "server_init_date"
	suggestedUsernamesKey           = "suggested_usernames"
	chatJoinMessagesEnabledKey      = "chat_join_messages_enabled"
	chatEstablishedUsersOnlyModeKey = "chat_established_users_only_mode"
	chatSpamProtectionEnabledKey    = "chat_spam_protection_enabled"
	chatSlurFilterEnabledKey        = "chat_slur_filter_enabled"
	chatRequireAuthenticationKey    = "chat_require_authentication"
	notificationsEnabledKey         = "notifications_enabled"
	// nolint:gosec
	hideViewerCountKey           = "hide_viewer_count"
	customOfflineMessageKey      = "custom_offline_message"
	customColorVariableValuesKey = "custom_color_variable_values"
	streamKeysKey                = "stream_keys"
	disableSearchIndexingKey     = "disable_search_indexing"
	videoServingEndpointKey      = "video_serving_endpoint"
	faviconPathKey               = "favicon_path"
)
